services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    ports:
      - "5056:5055"
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
