services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    ports:
      - "5000:5000"
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
