services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    ports:
      - "8787:8787"
    volumes:
      - ./config:/config
      - /data/media/books:/books
    environment:
      PUID: 1000
      PGID: 1000
