services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    restart: unless-stopped
    ports:
      - "6875:80"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
