services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
