services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8053:80"
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      TZ: America/Chicago
      WEBPASSWORD: MyPiholePassword123
      DNSSEC: "true"
    cap_add:
      - NET_ADMIN
