services:
  gotify:
    image: gotify/server:latest
    container_name: gotify
    restart: unless-stopped
    ports:
      - "8089:80"
    environment:
      TZ: America/Denver
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config:/config
