services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny
    ports:
      - "8095:8080"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
