services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    ports:
      - "9095:9090"
    environment:
      TZ: America/Denver
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config:/config
