services:
  autobrr:
    image: ghcr.io/autobrr/autobrr:latest
    container_name: autobrr
    restart: unless-stopped
    ports:
      - "7474:7474"
    environment:
      - TZ=America/Denver
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
