"""Generate per-stack .env files from mapped variables."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from composearr.central_env_analyzer import is_common_var, is_secret_var


def generate_env_content(
    stack_name: str,
    env_vars: dict[str, str],
    *,
    include_header: bool = True,
) -> str:
    """Generate .env file content for a single stack.

    Variables are grouped into sections:
    - Common (TZ, PUID, PGID, UMASK)
    - Stack-specific
    - Secrets (API keys, tokens, passwords)
    """
    lines: list[str] = []

    if include_header:
        timestamp = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
        lines.extend([
            f"# {stack_name} - Environment Variables",
            f"# Generated by ComposeArr on {timestamp}",
            "#",
            "# This file contains environment variables for this stack only.",
            "# Keep this file secure - do not commit to git.",
            "",
        ])

    # Categorize variables
    common: dict[str, str] = {}
    secrets: dict[str, str] = {}
    other: dict[str, str] = {}

    for var_name, value in env_vars.items():
        if is_common_var(var_name):
            common[var_name] = value
        elif is_secret_var(var_name):
            secrets[var_name] = value
        else:
            other[var_name] = value

    # Common section
    if common:
        lines.append("# Common")
        for var_name in sorted(common):
            lines.append(f"{var_name}={common[var_name]}")
        lines.append("")

    # Stack-specific section
    if other:
        lines.append("# Configuration")
        for var_name in sorted(other):
            lines.append(f"{var_name}={other[var_name]}")
        lines.append("")

    # Secrets section
    if secrets:
        lines.append("# Secrets")
        for var_name in sorted(secrets):
            lines.append(f"{var_name}={secrets[var_name]}")
        lines.append("")

    return "\n".join(lines)


def write_stack_env(
    stack_dir: Path,
    stack_name: str,
    env_vars: dict[str, str],
    *,
    overwrite: bool = False,
) -> Path:
    """Write a .env file to a stack directory.

    Args:
        stack_dir: Path to the stack directory.
        stack_name: Name of the stack (for header).
        env_vars: Variables to write.
        overwrite: If False, appends missing vars to existing file.

    Returns:
        Path to the written .env file.
    """
    env_path = stack_dir / ".env"

    if env_path.exists() and not overwrite:
        # Merge: add only variables not already present
        existing_content = env_path.read_text(encoding="utf-8")
        existing_vars = _parse_existing_vars(existing_content)

        new_vars = {k: v for k, v in env_vars.items() if k not in existing_vars}
        if new_vars:
            append_content = "\n# Added by ComposeArr\n"
            for var_name in sorted(new_vars):
                append_content += f"{var_name}={new_vars[var_name]}\n"
            env_path.write_text(
                existing_content.rstrip("\n") + "\n" + append_content,
                encoding="utf-8",
            )
    else:
        content = generate_env_content(stack_name, env_vars)
        env_path.write_text(content, encoding="utf-8")

    return env_path


def _parse_existing_vars(content: str) -> set[str]:
    """Extract variable names from existing .env content."""
    names: set[str] = set()
    for line in content.splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            name = line.split("=", 1)[0].strip()
            if name:
                names.add(name)
    return names
