services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    environment:
      TZ: America/Denver
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config:/config
