services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    restart: unless-stopped
    ports:
      - "2283:2283"
    environment:
      TZ: America/Denver
      PUID: 1000
      PGID: 1000
    volumes:
      - ./config:/config
